"""Линейки четвёртой версии: цепочки фрагментов и связные ядра.

ЖИВОЙ КОД ПЕРЕЕХАЛ в ``ocr_utils.page_layout.tables.rules``: здесь остался реэкспорт, чтобы стенд исследований
(сравнение версий, добыча, отчёты) мерил тот же детектор, что стоит в конвейере.
"""

from ocr_utils.page_layout.tables.rules import (  # noqa: F401 — реэкспорт для стенда
    FRAGMENT_MM,
    CHAIN_GAP_MM,
    CHAIN_SHORT_GAP_MM,
    CHAIN_LONG_MM,
    CHAIN_OFFSET_MM,
    CHAIN_ANGLE_DEG,
    ISOLATION_BAND_MM,
    MAX_ISOLATION,
    CROSS_TOL_MM,
    STACK_OVERLAP,
    STACK_GAP_MM,
    STACK_TOUCH_MM,
    COMPLETE_LONG_RULES,
    LONG_RULE_SPAN,
    ALIGNED_SHARE,
    ALIGNED_TOL_MM,
    Fragment,
    fragments,
    _predicted_across,
    continues,
    _components,
    _chain_edges,
    _merge,
    chain,
    isolation,
    find_rules,
    _as_fragment,
    _long_rules,
    _aligned,
    _bridged,
    _stacked,
    _overlapping,
    _should_merge,
    cores,
    _extent,
    _inside,
)

__all__ = [
    "FRAGMENT_MM",
    "CHAIN_GAP_MM",
    "CHAIN_SHORT_GAP_MM",
    "CHAIN_LONG_MM",
    "CHAIN_OFFSET_MM",
    "CHAIN_ANGLE_DEG",
    "ISOLATION_BAND_MM",
    "MAX_ISOLATION",
    "CROSS_TOL_MM",
    "STACK_OVERLAP",
    "STACK_GAP_MM",
    "STACK_TOUCH_MM",
    "COMPLETE_LONG_RULES",
    "LONG_RULE_SPAN",
    "ALIGNED_SHARE",
    "ALIGNED_TOL_MM",
    "Fragment",
    "fragments",
    "_predicted_across",
    "continues",
    "_components",
    "_chain_edges",
    "_merge",
    "chain",
    "isolation",
    "find_rules",
    "_as_fragment",
    "_long_rules",
    "_aligned",
    "_bridged",
    "_stacked",
    "_overlapping",
    "_should_merge",
    "cores",
    "_extent",
    "_inside",
]
