"""Проверка находки детектора: таблица это или что-то другое.

ЖИВОЙ КОД ПЕРЕЕХАЛ в ``ocr_utils.scan_markup.table_detection.verify``: здесь остался реэкспорт, чтобы стенд исследований
(сравнение версий, добыча, отчёты) мерил тот же детектор, что стоит в конвейере.
"""

from ocr_utils.scan_markup.table_detection.verify import (  # noqa: F401 — реэкспорт для стенда
    INNER_MARGIN_MM,
    GUTTER_MIN_MM,
    LINE_GAP_MM,
    CROSS_TOL_MM,
    Features,
    HEADER,
    CELL_INK_SHARE,
    MIN_INNER_VERTICAL,
    SINGLE_COLUMN_MIN_CELLS,
    SINGLE_COLUMN_GLYPH_OF_INK,
    MIN_GLYPH_OF_INK,
    CLEAR_GLYPH_OF_INK,
    STRONG_EDGE_FILL,
    PLAUSIBLE_EDGE_FILL,
    MANY_COLUMNS,
    is_table,
    FLOOR_GLYPH_OF_INK,
    FLOOR_FILLED_CELLS,
    BLANK_MIN_CELLS,
    BLANK_MIN_LATTICE,
    BLANK_MIN_FILLED,
    BANNER_MAX_CELLS,
    is_table_v3,
    _inner_counts,
    _gutters,
    _line_span,
    _lattice,
    _filled_cells,
    _edge_fill,
    features,
    glyph_mask,
)

__all__ = [
    "INNER_MARGIN_MM",
    "GUTTER_MIN_MM",
    "LINE_GAP_MM",
    "CROSS_TOL_MM",
    "Features",
    "HEADER",
    "CELL_INK_SHARE",
    "MIN_INNER_VERTICAL",
    "SINGLE_COLUMN_MIN_CELLS",
    "SINGLE_COLUMN_GLYPH_OF_INK",
    "MIN_GLYPH_OF_INK",
    "CLEAR_GLYPH_OF_INK",
    "STRONG_EDGE_FILL",
    "PLAUSIBLE_EDGE_FILL",
    "MANY_COLUMNS",
    "is_table",
    "FLOOR_GLYPH_OF_INK",
    "FLOOR_FILLED_CELLS",
    "BLANK_MIN_CELLS",
    "BLANK_MIN_LATTICE",
    "BLANK_MIN_FILLED",
    "BANNER_MAX_CELLS",
    "is_table_v3",
    "_inner_counts",
    "_gutters",
    "_line_span",
    "_lattice",
    "_filled_cells",
    "_edge_fill",
    "features",
    "glyph_mask",
]
